id: ACA78D6BA
title: Brief Sukhāvatī Aspiration
type: translation
pechas:
- I4EAF8611
- IA42A2D04
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:58:25.022100
  last_modified_at: 2023-01-04 11:58:25.022112
  collections:
  - Gyalse Shenpen Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  I4EAF8611/141A: AAC5
  IA42A2D04/CE17: AAC5
